### ISSUE TITLE
SmbTransport failed to reconnect after a server reboot

### ISSUE THREAD

**Issue by jhattab** [codelibs/jcifs#5]
Hi,
We have faced an issue with jcifs embedded in org.apache-extras.camel-extra:camel-jcifs.
Quick description :
When the samba server was restarted for updates or maintenance reasons, the jcifs library was not able to reconnect on port 445. And keeps falling at trying to reconnect on port 139.

With a first exception :

```
	Caused by: jcifs.smb.SmbException: The handle is invalid.
	at jcifs.smb.SmbTransport.checkStatus(SmbTransport.java:563)[306:jcifs:1.3.18]
	at jcifs.smb.SmbTransport.send(SmbTransport.java:663)[306:jcifs:1.3.18]
	at jcifs.smb.SmbSession.sessionSetup(SmbSession.java:390)[306:jcifs:1.3.18]
	at jcifs.smb.SmbSession.send(SmbSession.java:218)[306:jcifs:1.3.18]
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:176)[306:jcifs:1.3.18]
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:911)[306:jcifs:1.3.18]
	at jcifs.smb.SmbFile.connect(SmbFile.java:957)[306:jcifs:1.3.18]
	at jcifs.smb.SmbFile.connect0(SmbFile.java:880)[306:jcifs:1.3.18]
	at jcifs.smb.SmbFile.resolveDfs(SmbFile.java:669)[306:jcifs:1.3.18]
	at jcifs.smb.SmbFile.send(SmbFile.java:773)[306:jcifs:1.3.18]
	at jcifs.smb.SmbFile.doFindFirstNext(SmbFile.java:1989)[306:jcifs:1.3.18]
	at jcifs.smb.SmbFile.doEnum(SmbFile.java:1741)[306:jcifs:1.3.18]
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1718)[306:jcifs:1.3.18]
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1651)[306:jcifs:1.3.18]
```
And then a second that indicates the port 139 connection failure :
```
java.io.IOException: Failed to establish session with ---SERVER---
at jcifs.smb.SmbTransport.ssn139(SmbTransport.java:239)
at jcifs.smb.SmbTransport.negotiate(SmbTransport.java:249)
at jcifs.smb.SmbTransport.doConnect(SmbTransport.java:322)
at jcifs.util.transport.Transport.run(Transport.java:241)
at java.lang.Thread.run(Thread.java:745)

at jcifs.util.transport.Transport.run(Transport.java:258)
at java.lang.Thread.run(Thread.java:745)

at jcifs.smb.SmbTransport.connect(SmbTransport.java:309)[306:jcifs:1.3.18]
at jcifs.smb.SmbTree.treeConnect(SmbTree.java:156)[306:jcifs:1.3.18]
at jcifs.smb.SmbFile.doConnect(SmbFile.java:911)[306:jcifs:1.3.18]
at jcifs.smb.SmbFile.connect(SmbFile.java:957)[306:jcifs:1.3.18]
at jcifs.smb.SmbFile.connect0(SmbFile.java:880)[306:jcifs:1.3.18]
at jcifs.smb.SmbFile.resolveDfs(SmbFile.java:669)[306:jcifs:1.3.18]
at jcifs.smb.SmbFile.send(SmbFile.java:773)[306:jcifs:1.3.18]
at jcifs.smb.SmbFile.doFindFirstNext(SmbFile.java:1989)[306:jcifs:1.3.18]
at jcifs.smb.SmbFile.doEnum(SmbFile.java:1741)[306:jcifs:1.3.18]
at jcifs.smb.SmbFile.listFiles(SmbFile.java:1718)[306:jcifs:1.3.18]
at jcifs.smb.SmbFile.listFiles(SmbFile.java:1651)[306:jcifs:1.3.18]
```

In fact the jcifs is designed to switch between port 445 and 139, but in case of an IO exception the transport object doesn't switch anymore.

SmbTransport:312

```
    protected void doConnect() throws IOException {
        /*
         * Negotiate Protocol Request / Response
         */

        SmbComNegotiateResponse resp = new SmbComNegotiateResponse( server );
        try {
            negotiate( port, resp );
        } catch( ConnectException ce ) {
            port = (port == 0 || port == DEFAULT_PORT) ? 139 : DEFAULT_PORT;
            negotiate( port, resp );
        } catch( NoRouteToHostException nr ) {
            port = (port == 0 || port == DEFAULT_PORT) ? 139 : DEFAULT_PORT;
            negotiate( port, resp );
        }
```

Also I suggest to catch on IO Exception to switch on port 445. Like this the transport will be able to reconnect as soon as the server is back.

```
    protected void doConnect() throws IOException {
        /*
         * Negotiate Protocol Request / Response
         */

        SmbComNegotiateResponse resp = new SmbComNegotiateResponse( server );
        try {
            negotiate( port, resp );
        } catch( ConnectException ce ) {
            port = (port == 0 || port == DEFAULT_PORT) ? 139 : DEFAULT_PORT;
            negotiate( port, resp );
        } catch( NoRouteToHostException nr ) {
            port = (port == 0 || port == DEFAULT_PORT) ? 139 : DEFAULT_PORT;
            negotiate( port, resp );
        } catch( IOException ioe ) {
            port = (port == 0 || port == DEFAULT_PORT) ? 139 : DEFAULT_PORT;
            throw ioe;
        }
```

**Comment by Nehapatelr11** [comment]
Hi
We have faced an issue with jcifs

Issue: when the samba server reboot then it trying to connect to 139 port but it does not recognise the
DNS name in that.So it failed to connect

Preferable solution: we have not change the code in jcifs jar but handle that particular exception and 
close the transport.So  next time server will up it will create new Transport and the things will work.
