### ISSUE TITLE
Deadlock when attempting to connect to a device you cannot reach

### ISSUE THREAD

**Issue by nmesh** [codelibs/jcifs#9]
Here is a snippet of the stack on the deadlocked threads, down in the jcifs-ng code:

```
"Thread-75@7008" prio=5 tid=0x1aa nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks Thread-75@7008
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:407)
	  at java.lang.Thread.join(Thread.java:1291)
	  - locked <0x1b71> (a java.lang.Object)
	  at java.lang.Thread.join(Thread.java:1367)
	  at jcifs.util.transport.Transport.cleanupThread(Transport.java:636)
	  - locked <0x1b72> (a jcifs.smb.SmbTransportImpl)
	  at jcifs.util.transport.Transport.connect(Transport.java:586)
	  - locked <0x1b72> (a jcifs.smb.SmbTransportImpl)
	  - locked <0x1b61> (a java.lang.Thread)
	  at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:668)
	  at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:213)
	  at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47)
	  at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560)
	  - locked <0x1b74> (a jcifs.smb.SmbTreeConnection)
	  at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	  - locked <0x1b74> (a jcifs.smb.SmbTreeConnection)
	  at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	  - locked <0x1b74> (a jcifs.smb.SmbTreeConnection)
	  at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	  at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:550)
	  - locked <0x1b75> (a jcifs.smb.SmbFile)
	  at jcifs.smb.SmbFile.exists(SmbFile.java:826)
	  (snipped out client code...)
```
The join called from cleanupThread is waiting on Transport2@7009:
```
"Transport2@7009" daemon prio=5 tid=0x1ab nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for Thread-75@7008 to release lock on <0x1b61> (a java.lang.Thread)
	  at jcifs.util.transport.Transport.run(Transport.java:733)
	  at java.lang.Thread.run(Thread.java:762)
```

You can see in thread Thread-75@7008 that you are locked on <0x1b61> which is acquired in jcifs.util.transport.Transport.connect (parent of jcifs.smb.SmbTransportImpl) on line 578.  And then you're trying to acquire that object in thread Transport2@7009 (spawned by thread Thread-75@7008 in Transport.connect line 579) in jcifs.util.transport.Transport.run on line 733.  Boom... Deadlock.  This sequence of events is reproducible every single time in my setup, though the thread names may vary.

You need to restructure thread cleanup so that you move the join outside of the synchronized block *or* use a lock object that can be interrupted instead of a synchronized block that cannot be interrupted.

**Comment by marevol** [comment]
What version did you use?

**Comment by nmesh** [comment]
Originally 2.1.0, but I fetched latest, built, and tried it with the same results.

**Comment by marevol** [comment]
I added https://github.com/codelibs/jcifs/commit/8aaf13a932533980f77b714c53913bf959bb790f.
If you have a problem, please let me know.
